name: commit

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/

      - name: test
        run: |
          yarn install
          yarn test